version: "3"

services:

  notifications-sdk-csharp-preview-build:
    build: .
    container_name: notifications-sdk-csharp-preview-build
    image: finbourne/notifications-sdk-csharp-preview-build
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_NOTIFICATIONS_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src